### ISSUE TITLE
sane release procedure

### ISSUE THREAD

**Issue by lukasheinrich** [recast-hep/recast-atlas#42]
i'm ashamed of this repo @matthewfeickert :-p

**Comment by matthewfeickert** [comment]
> i'm ashamed of this repo @matthewfeickert :-p

Nothing to be ashamed about when you're making useful and impactful things! :D 

If I can be a source of help rather than a source of shame let me know how I can help you. :rocket:

**Comment by matthewfeickert** [comment]
This is being resolved across:
- PR #57
- PR #60
- PR #61
