### ISSUE TITLE
Workflow visualization shows only square glyphs in place of titles since v0.1.1

### ISSUE THREAD

**Issue by robinnewhouse** [recast-hep/recast-atlas#67]
In versions `0.1.1` through `0.1.8` (latest), when running recast workflows, the workflow visualization lacks titles for each of the steps and artefacts. In place, square placeholder glyphs are used. It appears that all workflow steps are in the correct places with the expected layout, but there are no titles. If I downgrade to recast 0.1.0, the titles in the workflow return to normal.

This issue appears in the .gif, .png, and .pdf versions of the visualization.

I am running macOS Big Sur 11.6 (20G165)

---

This can be minimally reproduced with the following:

```console
pip install recast-atlas==0.1.0
recast run examples/rome
```

which produces `_yadage/yadage_workflow_instance.png` of

![yadage_workflow_instance](https://user-images.githubusercontent.com/2333799/137201617-f753d383-d0da-4438-aa7e-9dae3446e712.png)

compared to

```console
pip install recast-atlas==0.1.1
recast run examples/rome
```
![yadage_workflow_instance-1](https://user-images.githubusercontent.com/2333799/137201722-26b68fba-e574-4890-9995-4b0062746e18.png)

**Comment by matthewfeickert** [comment]
Thanks for the Issue @robinnewhouse. Can you also give us the Python runtime version that you're using in your virtual environment? So the output of

```console
$ python --version --version
```

**Comment by matthewfeickert** [comment]
> In this instance, I'm using neither and my python version is `Python 2.7.16`.

Okay thanks. I ask only so that I can try to replicate your working environment when debugging with you.

> I guess I very rarely use my local python, and I admit, I typically use conda instead of venv

That's fine. I'm using "virtual environment" here to mean it in the most broad sense (so a venv env and a Conda env both count)

>  I'm upgrading to 3 right away ;)

:snake: `recast-atlas` has CI covering Python 3.6 - Python 3.8 (and should have Python 3.9 and Python 3.10 support soon) so I think you should be good to go there as long as you're in the currently supported range.

**Comment by lukasheinrich** [comment]
mayb it's som `libgraphviz` related issue

**Comment by matthewfeickert** [comment]
> That might help debug it

Indeed.

```console
$ docker pull recast/recastatlas:v0.1.8
$ docker run --rm -ti -v $PWD:/work recast/recastatlas:v0.1.8
/work # cat test.gv 
strict digraph {
   A -> B;
}
/work # dot -Tpdf test.gv -o test.pdf
/work # dot -Tpng test.gv -o test.png
```

produces this `test.png`

![test](https://user-images.githubusercontent.com/5142394/138329402-e8d1bc59-5e58-4390-8bb8-18c36e42c0a8.png)

I have a branch (`docker/update-dockerfile`) that is trying to get a `python:3.8-slim-bullseye` based image working which is able to render this correctly

```console
$ docker run --rm -ti -v $PWD:/work recast/recastatlas:debug 
root@d5e1c4970e41:/work# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@d5e1c4970e41:/work# dot -Tpdf test.gv -o test.pdf
root@d5e1c4970e41:/work# dot -Tpng test.gv -o test.png
root@d5e1c4970e41:/work# 
```

![test_working](https://user-images.githubusercontent.com/5142394/138330265-acef8695-6c1a-41a4-874c-9611d0bfd0d7.png)

but I need to figure out how to get `docker` working in this image for it to be useful.

**Comment by lukasheinrich** [comment]
this is what yadag runs, so if `dot` works yadag viz should also work:

https://github.com/yadage/yadage/blob/master/yadage/visualize.py#L121
